tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "caskroom/cask"
brew "wget"
brew "iterm2"
brew "git-lfs"
brew "docker-completion"
brew "pip-completion"
brew "zsh"
brew "zsh-completions"
brwe "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
cask "google-chrome"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "google-cloud-sdk"
cask "kdiff3"
cask "zoom"
cask "notion"
cask "caskroom/fonts/font-fira-code"
cask "caskroom/fonts/font-fira-mono-for-powerline"
cask "caskroom/fonts/font-inconsolata"
mas "Amphetamine", id: 937984704
mas "XCode", id: 497799835