config:
  partial_parse: true
  use_colors: true
  send_anonymous_usage_stats: false

tradify-hq:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: tradify-214020
      dataset: tradify_hq_[insert your username here] # You can also use "schema" here
      threads: 4
      priority: interactive
      timeout_seconds: 300
      retries: 1
      #impersonate_service_account: dbt-runner@yourproject.iam.gserviceaccount.com